# Generated by Django 2.1.15 on 2020-04-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfc_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('nfc_store_id', models.CharField(blank=True, max_length=100, null=True)),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_address', models.CharField(blank=True, max_length=100, null=True)),
                ('store_postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('stroe_city', models.CharField(blank=True, max_length=100, null=True)),
                ('store_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('longtitude', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
    ]
